### ISSUE TITLE
헤더 메뉴 글자수 초과 수정요청.

### ISSUE THREAD

**Issue by jodongguk** [rhkanrdl/openos-new#1]
## 헤더 메뉴리스트
글자수가 많아져서 발생되는 메뉴 스타일 수정요청드립니다.

![image](https://cloud.githubusercontent.com/assets/16861058/22892806/208506e0-f257-11e6-9b87-f1dcf14d06c4.png)

**Comment by rhkanrdl** [comment]
수정완료

**Comment by rhkanrdl** [comment]
수정완료

**Comment by rhkanrdl** [comment]
수정완료
